gallery-before/config/routes.rb
Gallery::Application.routes.draw do
  resources :paintings
  root to: 'paintings#index'
end

gallery-before/app/models/painting.rb
class Painting < ActiveRecord::Base
  attr_accessible :image, :name
  mount_uploader :image, ImageUploader
end

gallery-before/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

gallery-before/app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  def index
    @paintings = Painting.all
  end

  def show
    @painting = Painting.find(params[:id])
  end

  def new
    @painting = Painting.new
  end

  def create
    @painting = Painting.new(params[:painting])
    if @painting.save
      redirect_to paintings_url, notice: "Painting was successfully created."
    else
      render :new
    end
  end

  def edit
    @painting = Painting.find(params[:id])
  end

  def update
    @painting = Painting.find(params[:id])
    if @painting.update_attributes(params[:painting])
      redirect_to paintings_url, notice: "Painting was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @painting = Painting.find(params[:id])
    @painting.destroy
    redirect_to paintings_url, notice: "Painting was successfully destroyed."
  end
end

gallery-before/app/helpers/application_helper.rb
module ApplicationHelper
end

gallery-before/app/helpers/paintings_helper.rb
module PaintingsHelper
end

gallery-before/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Painting Gallery</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

gallery-before/app/views/paintings/_form.html.erb
<%= form_for @painting do |f| %>
  <% if @painting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@painting.errors.count, "error") %> prohibited this painting from being saved:</h2>
      <ul>
      <% @painting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

gallery-before/app/views/paintings/_painting.html.erb
<div class="painting">
  <%= link_to image_tag(painting.image_url(:thumb)), painting if painting.image? %>
  <div class="name"><%= painting.name %></div>
  <div class="actions">
    <%= link_to "edit", edit_painting_path(painting) %> |
    <%= link_to "remove", painting, :confirm => 'Are you sure?', :method => :delete %>
  </div>
</div>

gallery-before/app/views/paintings/edit.html.erb
<h1>Editing Painting</h1>

<%= render 'form' %>

gallery-before/app/views/paintings/index.html.erb
<h1>Painting Gallery</h1>

<div id="paintings">
  <%= render @paintings %>
</div>
<div class="clear"></div>

<p><%= link_to "Add a Painting", new_painting_path %></p>

gallery-before/app/views/paintings/new.html.erb
<h1>Add a Painting</h1>

<%= render 'form' %>

gallery-before/app/views/paintings/show.html.erb
<h1><%= @painting.name %></h1>

<p><%= image_tag @painting.image_url %></p>

<p>
  <%= link_to "Edit", edit_painting_path(@painting) %> |
  <%= link_to "Destroy", @painting, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "Back to Paintings", paintings_path %>
</p>